<?php
/**
 * This file is part of PHP CS Fixer.
 *
 * (c) vinhson <15227736751@qq.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */
namespace App\Model;

use App\Events\RegisterSendMail;
use App\Observers\AdminUserObserve;
use Illuminate\Database\Eloquent\Model;

class AdminUser extends Model
{
    protected $guarded = [];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::observe(AdminUserObserve::class);
    }

    /**
     * 模型事件 <==> event(new RegisterSendMail($re));
     * @var array
     */
    protected $dispatchesEvents = [
        'creating' => RegisterSendMail::class,
    ];
}
