<?php
/**
 * This file is part of PHP CS Fixer.
 *
 * (c) vinhson <15227736751@qq.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */
namespace App\Model;

use Request;
use Carbon\Carbon;
use Illuminate\Support\Str;
use Laravel\Scout\Searchable;
use Illuminate\Support\Facades\Redis;
use James\Eloquent\Filter\FilterTrait;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use Searchable;
    use FilterTrait;

    public $asYouType = true;

    protected $casts = [
        'label_id' => 'array',
    ];

    protected $appends = ['time'];

    /**
     * Get the indexable data array for the model.
     *
     * @return array
     */
    public function toSearchableArray()
    {
        return $this->only('id', 'name', 'content');
    }

    /**
     * 关联用户表
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(AdminUser::class);
    }

    /**
     * 关联访问记录表
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function record()
    {
        return $this->hasMany(ArticleRecord::class);
    }

    /**
     * 文章评论
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function discuss()
    {
        return $this->hasMany(Discuss::class);
    }

    /**
     * 关联删除
     */
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($acticle) {
            $acticle->record()->delete();
            $acticle->discuss()->delete();
            Redis::connection('article')->zrem('article', $acticle->id);
        });
    }

    /**
     * 访问器
     * @return mixed
     */
    public function getTimeAttribute()
    {
        return Carbon::parse($this->created_at)->diffForHumans();
    }

    public function getContentAttribute($value)
    {
        $string = Request::getRequestUri();

        if (Str::startsWith($string, '/admins') || Str::startsWith($string, '/articles')) {
            return $value;
        }

        return str_limit($value, 150);
    }

    /**
     * 搜索
     * @param $query
     * @param $name
     * @return mixed
     */
    public function scopeStatus($query)
    {
        return $query->where('status', '<>', 2);
    }

    public function scopeOfTag($query, $tag)
    {
        $label_id = $tag ? Label::where('title', $tag)->value('id') : '';

        return $label_id ? $query->where('label_id', 'like', '%"' . $label_id . '"%') : $query;
    }

    public function scopeOfAuthor($query, $authore)
    {
        $user_id = $authore ? AdminUser::where('name', $authore)->value('id') : '';

        return $user_id ? $query->where('user_id', $user_id) : $query;
    }
}
