<?php

namespace App\Model;

use App\Events\ReplySendMail;
use App\Observers\DiscussObserve;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use James\Eloquent\Filter\FilterTrait;

class Discuss extends Model
{
    const STATUS_SHOW = 1;  // 显示
    const STATUS_HIDE = 2;  // 不显示
    const STATUS_TOP = 3;   // 置顶

    protected $table = 'discuss';

    protected $guarded = [];

    public static $status_name = [
        self::STATUS_SHOW => '显示',
        self::STATUS_HIDE => '不显示',
        self::STATUS_TOP => '置顶',
    ];

    use FilterTrait;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::observe(DiscussObserve::class);
    }

    public function article()
    {
        return $this->belongsTo(Article::class);
    }

    public function oauth()
    {
        return $this->belongsTo(Oauth::class)->withDefault(['username' => 'james', 'email' => env('MAIL_USERNAME'), 'image' => 'images/favicon.jpg']);
    }

    public function scopeStatus($query, $status)
    {
        return $query->where('status', $status);
    }

    public function scopePpid($query, $ppid)
    {
        return $query->where('ppid', $ppid);
    }

    /**
     * 评论
     * @param $data
     * @return bool
     */
    protected static function store($data)
    {
        if($re = self::where('id', $data['pid'])->first()){
            if($re->status == 3)
                $data['ppid'] = $re->id;
            else{
                if($re->pid == 0)
                    $data['ppid'] = $re->id;
                else
                    $data['ppid'] = $re->ppid;
            }
        }else
            $data['ppid'] = 0;

        return self::create($data + ['created_at' => Carbon::now('Asia/Shanghai'), 'updated_at' => Carbon::now('Asia/Shanghai')]);
    }
}
