<?php
/**
 * This file is part of PHP CS Fixer.
 *
 * (c) vinhson <15227736751@qq.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */
namespace App\Model;

use Carbon\Carbon;
use App\Observers\DiscussObserve;
use James\Eloquent\Filter\FilterTrait;
use Illuminate\Database\Eloquent\Model;

class Discuss extends Model
{
    use FilterTrait;
    public const STATUS_SHOW = 1;  // 显示
    public const STATUS_HIDE = 2;  // 不显示
    public const STATUS_TOP = 3;   // 置顶

    protected $table = 'discuss';

    protected $guarded = [];

    public static $status_name = [
        self::STATUS_SHOW => '显示',
        self::STATUS_HIDE => '不显示',
        self::STATUS_TOP => '置顶',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::observe(DiscussObserve::class);
    }

    public function article()
    {
        return $this->belongsTo(Article::class);
    }

    public function oauth()
    {
        return $this->belongsTo(Oauth::class)->withDefault(['username' => 'james', 'email' => env('MAIL_USERNAME'), 'image' => 'images/favicon.jpg']);
    }

    public function scopeStatus($query, $status)
    {
        return $query->where('status', $status);
    }

    public function scopePpid($query, $ppid)
    {
        return $query->where('ppid', $ppid);
    }

    /**
     * 评论
     * @param $data
     * @return bool
     */
    protected static function store($data)
    {
        if ($re = self::where('id', $data['pid'])->first()) {
            if ($re->status == 3) {
                $data['ppid'] = $re->id;
            } else {
                if ($re->pid == 0) {
                    $data['ppid'] = $re->id;
                } else {
                    $data['ppid'] = $re->ppid;
                }
            }
        } else {
            $data['ppid'] = 0;
        }

        return self::create($data + ['created_at' => Carbon::now('Asia/Shanghai'), 'updated_at' => Carbon::now('Asia/Shanghai')]);
    }
}
